name: json_sentinel
description: Lightweight runtime JSON key and type validation for Dart. No code generation required.
version: 0.1.1
repository: https://github.com/IgeeTheron/json-sentinel
issue_tracker: https://github.com/IgeeTheron/json-sentinel/issues

topics:
  - json
  - validation
  - schema-validation

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.1
